export class BookmarkActions {

  static GET_ALL_BOOKMARKS = 'GET_ALL_BOOKMARKS';
  static GET_ALL_BOOKMARKS_SUCCESS = 'GET_ALL_BOOKMARKS_SUCCESS';
  static GET_ALL_BOOKMARKS_FAILED = 'GET_ALL_BOOKMARKS_FAILED';

}
