export class BookmarkActions {

  static DELETE_BOOKMARK = 'DELETE_BOOKMARK';
  static DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
  static DELETE_BOOKMARK_FAILED = 'DELETE_BOOKMARK_FAILED';

  static GET_BOOKMARKS = 'GET_BOOKMARKS';
  static GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
  static GET_BOOKMARKS_FAILED = 'GET_BOOKMARKS_FAILED';

  static BOOKMARK = 'BOOKMARK';
  static BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS';
  static BOOKMARK_FAILED = 'BOOKMARK_FAILED';

  static GET_BOOKMARKS_COUNT = 'GET_BOOKMARKS_COUNT';
  static GET_BOOKMARKS_COUNT_SUCCESS = 'GET_BOOKMARKS_COUNT_SUCCESS';
  static GET_BOOKMARKS_COUNT_FAILED = 'GET_BOOKMARKS_COUNT_FAILED';

}
