export class BookmarkActions {

  static GET_ALL_BOOKMARKS = 'GET_ALL_BOOKMARKS';
  static GET_ALL_BOOKMARKS_SUCCESS = 'GET_ALL_BOOKMARKS_SUCCESS';
  static GET_ALL_BOOKMARKS_FAILED = 'GET_ALL_BOOKMARKS_FAILED';

  static BOOKMARK = 'BOOKMARK';
  static BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS';
  static BOOKMARK_FAILED = 'BOOKMARK_FAILED';

}
