import { Action } from '@ngrx/store';

export class CommunitiesActions {
    static COMMUNITY_CREATE = 'COMMUNITY_CREATE';
    static COMMUNITY_CREATE_SUCCESS = 'COMMUNITY_CREATE_SUCCESS';
    static COMMUNITY_CREATE_FAILED = 'COMMUNITY_CREATE_FAILED';

    static COMMUNITY_LIST = 'COMMUNITY_LIST';
    static COMMUNITY_LIST_SUCCESS = 'COMMUNITY_LIST_SUCCESS';
    static COMMUNITY_LIST_FAILED = 'COMMUNITY_LIST_FAILED';

    static COMMUNITY_JOIN = 'COMMUNITY_JOIN';
    static COMMUNITY_JOIN_SUCCESS = 'COMMUNITY_JOIN_SUCCESS';
    static COMMUNITY_JOIN_FAILED = 'COMMUNITY_JOIN_FAILED';

}
