export class DirectoryActions {

    static LOAD_DIRECTORY = 'LOAD_DIRECTORY';
    static LOAD_DIRECTORY_SUCCESS = 'LOAD_DIRECTORY_SUCCESS';
    static LOAD_DIRECTORY_FAILED = 'LOAD_DIRECTORY_FAILED';

    static GET_PROFILE = 'GET_PROFILE';
    static GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
    static GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

}
