import { Action } from '@ngrx/store';

export class EventActions {
    static EVENT_REG = 'EVENT_REG';
    static EVENT_REG_SUCCESS = 'EVENT_REG_SUCCESS';
    static EVENT_REG_FAILED = 'EVENT_REG_FAILED';

    static EVENT_DETAILS_LOAD = 'EVENT_DETAILS_LOAD ';
    static EVENT_DETAILS_LOAD_SUCCESS = 'EVENT_DETAILS_LOAD_SUCCESS';
    static EVENT_DETAILS_LOAD_FAILED = 'EVENT_DETAILS_LOAD_FAILED';

    static GET_ALL_INDUSTRY = 'GET_ALL_INDUSTRY';
    static GET_ALL_INDUSTRY_SUCCESS = 'GET_ALL_INDUSTRY_SUCCESS';
    static GET_ALL_INDUSTRY_FAILED = 'GET_ALL_INDUSTRY_FAILED';

    static FILE_UPLOAD = 'FILE_UPLOAD';
    static FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
    static FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';

    static EVENT_LIST = 'EVENT_LIST';
    static EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
    static EVENT_LIST_FAILED = 'EVENT_LIST_FAILED';

    static EVENT_ATTEND = 'EVENT_ATTEND';
    static EVENT_ATTEND_SUCCESS = 'EVENT_ATTEND_SUCCESS';
    static EVENT_ATTENDT_FAILED = 'EVENT_ATTEND_FAILED';

    static EVENT_SEARCH = 'EVENT_SEARCH';
    static EVENT_SEARCH_SUCCESS = 'EVENT_SEARCH_SUCCESS';
    static EVENT_SEARCH_FAILED = 'EVENT_SEARCH_FAILED';
}
