export class EventActions {

    static EVENT_BOOKAMRK_FLAG_UPDATE = 'EVENT_BOOKAMRK_FLAG_UPDATE';

    static GET_EVENT_TYPE = 'GET_EVENT_TYPE';
    static GET_EVENT_TYPE_SUCCESS = 'GET_EVENT_TYPE_SUCCESS';
    static GET_EVENT_TYPE_FAILED = 'GET_EVENT_TYPE_FAILED';

    static EVENT_EDIT = 'EVENT_EDIT';
    static EVENT_EDIT_SUCCESS = 'EVENT_EDIT_SUCCESS';
    static EVENT_EDIT_FAILED = 'EVENT_EDIT_FAILED';

    static EVENT_DELETE = 'EVENT_DELETE';
    static EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
    static EVENT_DELETE_FAILED = 'EVENT_DELETE_FAILED';

    static BANNER_SEARCH = 'BANNER_SEARCH';
    static BANNER_SEARCH_SUCCESS = 'BANNER_SEARCH_SUCCESS';
    static BANNER_SEARCH_FAILED = 'BANNER_SEARCH_FAILED';

    static EVENT_ATTENDEE_LOAD = 'EVENT_ATTENDEE_LOAD';
    static EVENT_ATTENDEE_LOAD_SUCCESS = 'EVENT_ATTENDEE_LOAD_SUCCES';
    static EVENT_ATTENDEE_LOAD_FAILED = 'EVENT_ATTENDEE_LOAD_FAILED';

    static EVENT_REG = 'EVENT_REG';
    static EVENT_REG_SUCCESS = 'EVENT_REG_SUCCESS';
    static EVENT_REG_FAILED = 'EVENT_REG_FAILED';

    static EVENT_DETAILS_LOAD = 'EVENT_DETAILS_LOAD ';
    static EVENT_DETAILS_LOAD_SUCCESS = 'EVENT_DETAILS_LOAD_SUCCESS';
    static EVENT_DETAILS_LOAD_FAILED = 'EVENT_DETAILS_LOAD_FAILED';

    static GET_ALL_INDUSTRY = 'GET_ALL_INDUSTRY';
    static GET_ALL_INDUSTRY_SUCCESS = 'GET_ALL_INDUSTRY_SUCCESS';
    static GET_ALL_INDUSTRY_FAILED = 'GET_ALL_INDUSTRY_FAILED';

    static FILE_UPLOAD = 'FILE_UPLOAD';
    static FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
    static FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';

    static EVENT_LIST = 'EVENT_LIST';
    static EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
    static EVENT_LIST_FAILED = 'EVENT_LIST_FAILED';

    static EVENT_ATTEND = 'EVENT_ATTEND';
    static EVENT_ATTEND_SUCCESS = 'EVENT_ATTEND_SUCCESS';
    static EVENT_ATTENDT_FAILED = 'EVENT_ATTEND_FAILED';

    static EVENT_SEARCH = 'EVENT_SEARCH';
    static EVENT_SEARCH_SUCCESS = 'EVENT_SEARCH_SUCCESS';
    static EVENT_SEARCH_FAILED = 'EVENT_SEARCH_FAILED';

    static EVENT_TYPE_LOAD = 'EVENT_TYPE_LOAD';
    static EVENT_TYPE_LOAD_SUCCESS = 'EVENT_TYPE_LOAD_SUCCESS';
    static EVENT_TYPE_LOAD_FAILED = 'EVENT_TYPE_LOAD_FAILED';

    static DWC_CONTACT_FORM = 'DWC_CONTACT_FORM';
    static DWC_CONTACT_FORM_SUCCESS = 'DWC_CONTACT_FORM_SUCCESS';
    static DWC_CONTACT_FORM_FAILED = 'DWC_CONTACT_FORM_FAILED';

    // DWC Payment request
    static DWC_PAYMENT_REQUEST = 'DWC_PAYMENT_REQUEST';
    static DWC_PAYMENT_REQUEST_SUCCESS = 'DWC_PAYMENT_REQUEST_SUCCESS';
    static DWC_PAYMENT_REQUEST_FAILED = 'DWC_PAYMENT_REQUEST_FAILED';

    // event dwc reg
    static DWC_EVENT_REG = 'DWC_EVENT_REG';
    static DWC_EVENT_REG_SUCCESS = 'DWC_EVENT_REG_SUCCESS';
    static DWC_EVENT_REG_FAILED = 'DWC_EVENT_REG_FAILED';
}
