import { Action } from '@ngrx/store';

export class ExploreActions {

    static LOAD_SPOTFEEDS = 'LOAD_SPOTFEEDS';
    static LOAD_SPOTFEEDS_SUCCESS = 'LOAD_SPOTFEEDS_SUCCESS';
    static LOAD_SPOTFEEDS_FAILED = 'LOAD_SPOTFEEDS_FAILED';

    static GET_EXPLORE_DATA = 'GET_EXPLORE_DATA';
    static GET_EXPLORE_DATA_SUCCESS = 'GET_EXPLORE_DATA_SUCCESS';
    static GET_EXPLORE_DATA_FAILED = 'GET_EXPLORE_DATA_FAILED';

    static EXPLORE_MEDIA_POST_DELETE = 'EXPLORE_MEDIA_POST_DELETE';
    static EXPLORE_MEDIA_POST_DELETE_SUCCESS = 'EXPLORE_MEDIA_POST_DELETE_SUCCESS';
    static EXPLORE_MEDIA_POST_DELETE_FAILED = 'EXPLORE_MEDIA_POST_DELETE_FAILED';

}
