export class MessageActions {

  static ADD_TO_MESSANGER_LIST = 'ADD_TO_MESSANGER_LIST';
  static ADD_TO_MESSANGER_LIST_SUCCESS = 'ADD_TO_MESSANGER_LIST_SUCCESS';
  static ADD_TO_MESSANGER_LIST_FAILED = 'ADD_TO_MESSANGER_LIST_FAILED';

  static LOAD_USER_PROFILE_DATA = 'LOAD_USER_PROFILE_DATA';
  static LOAD_USER_PROFILE_DATA_SUCCESS = 'LOAD_USER_PROFILE_DATA_SUCCESS';
  static LOAD_USER_PROFILE_DATA_FAILED = 'LOAD_USER_PROFILE_DATA_FAILED';

  static GET_RECEIPIENT = 'GET_RECEIPIENT';
  static GET_RECEIPIENT_SUCCESS = 'GET_RECEIPIENT_SUCCESS';
  static GET_RECEIPIENT_FAILED = 'GET_RECEIPIENT_FAILED';

  static GET_MESSANGER_LIST = 'GET_MESSANGER_LIST';
  static GET_MESSANGER_LIST_SUCCESS = 'GET_MESSANGER_LIST_SUCCESS';
  static GET_MESSANGER_LIST_FAILED = 'GET_MESSANGER_LIST_FAILED';

  static LOAD_CONVERSATION = 'LOAD_CONVERSATION';
  static LOAD_CONVERSATION_SUCCESS = 'LOAD_CONVERSATION_SUCCESS';
  static LOAD_CONVERSATION_FAILED = 'LOAD_CONVERSATION_FAILED';

  static SEND_MESSAGE = 'SEND_MESSAGE';
  static SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
  static SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

  static ADD_PUSHER_MESSAGE = 'ADD_PUSHER_MESSAGE';
  static ADD_PUSHER_MESSAGE_SUCCESS = 'ADD_PUSHER_MESSAGE_SUCCESS';
  static ADD_PUSHER_MESSAGE_FAILED = 'ADD_PUSHER_MESSAGE_FAILED';

  static RESET_CONVERSATION_STATE = 'RESET_CONVERSATION_STATE';

  static MESSAGE_SEARCH_USER = 'MESSAGE_SEARCH_USER';
  static MESSAGE_SEARCH_USER_SUCCESS = 'MESSAGE_SEARCH_USER_SUCCESS';
  static MESSAGE_SEARCH_USER_FAILED = 'MESSAGE_SEARCH_USER_FAILED';

  static PREPEND_ELEMENT_TO_USER_LIST = 'PREPEND_ELEMENT_TO_USER_LIST';

  static NETWORK_REQUEST_ACTION = 'NETWORK_REQUEST_ACTION';
  static NETWORK_REQUEST_ACTION_SUCCESS = 'NETWORK_REQUEST_ACTION_SUCCESS';
  static NETWORK_REQUEST_ACTION_FAILED = 'NETWORK_REQUEST_ACTION_FAILED';

  static USER_IS_TYPING = 'USER_IS_TYPING';
  static USER_IS_TYPING_SUCCESS = 'USER_IS_TYPING_SUCCESS';
  static USER_IS_TYPING_FAILED = 'USER_IS_TYPING_FAILED';

  static DELETE_MESSAGE = 'DELETE_MESSAGE';
  static DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
  static DELETE_MESSAGE_FAILED = 'DELETE_MESSAGE_FAILED';

  static NETWORK_REQUEST_DECLINE = 'NETWORK_REQUEST_DECLINE';

}
