export class NotificationActions {

  static GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
  static GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
  static GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';

  static MARK_AS_READ = 'MARK_AS_READ';
  static MARK_AS_READ_SUCCESS = 'MARK_AS_READ_SUCCESS';
  static MARK_AS_READ_FAILED = 'MARK_AS_READ_FAILED';

  static MARK_AS_ALL_READ = 'MARK_AS_ALL_READ';
  static MARK_AS_ALL_READ_SUCCESS = 'MARK_AS_ALL_READ_SUCCESS';
  static MARK_AS_ALL_READ_FAILED = 'MARK_AS_ALL_READ_FAILED';

  static ADD_PUSHER_NOTIFICATION = 'ADD_PUSHER_NOTIFICATION';
  static ADD_PUSHER_NOTIFICATION_SUCCESS = 'ADD_PUSHER_NOTIFICATION_SUCCESS';
  static ADD_PUSHER_NOTIFICATION_FAILED = 'ADD_PUSHER_NOTIFICATION_FAILED';

}
