import { Action } from '@ngrx/store';

export class NotificationActions {

  static LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
  static LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
  static LOAD_NOTIFICATIONS_FAILED = 'LOAD_NOTIFICATIONS_FAILED';

  static MARK_AS_READ = 'MARK_AS_READ';
  static MARK_AS_READ_SUCCESS = 'MARK_AS_READ_SUCCESS';
  static MARK_AS_READ_FAILED = 'MARK_AS_READ_FAILED';

  static MARK_AS_ALL_READ = 'MARK_AS_ALL_READ';
  static MARK_AS_ALL_READ_SUCCESS = 'MARK_AS_ALL_READ_SUCCESS';
  static MARK_AS_ALL_READ_FAILED = 'MARK_AS_ALL_READ_FAILED';

  static ADD_PUSHER_NOTIFICATIONS = 'ADD_PUSHER_NOTIFICATIONS';
  static ADD_PUSHER_NOTIFICATIONS_SUCCESS = 'ADD_PUSHER_NOTIFICATIONS_SUCCESS';
  static ADD_PUSHER_NOTIFICATIONS_FAILED = 'ADD_PUSHER_NOTIFICATIONS_FAILED';

}
