export class OpportunityActions {

    static CREATE_OPPORTUNITY = 'CREATE_OPPORTUNITY';
    static CREATE_OPPORTUNITY_SUCCESS = 'CREATE_OPPORTUNITY_SUCCESS';
    static CREATE_OPPORTUNITY_FAILED = 'CREATE_OPPORTUNITY_FAILED';

    static SEARCH_OPPORTUNITIES = 'SEARCH_OPPORTUNITIES';
    static SEARCH_OPPORTUNITIES_SUCCESS = 'SEARCH_OPPORTUNITIES_SUCCESS';
    static SEARCH_OPPORTUNITIES_FAILED = 'SEARCH_OPPORTUNITIES_FAILED';

}
