export class OpportunityActions {

    static CREATE_OPPORTUNITY = 'CREATE_OPPORTUNITY';
    static CREATE_OPPORTUNITY_SUCCESS = 'CREATE_OPPORTUNITY_SUCCESS';
    static CREATE_OPPORTUNITY_FAILED = 'CREATE_OPPORTUNITY_FAILED';

    static FILE_UPLOAD = 'FILE_UPLOAD';
    static FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
    static FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';

    static SEARCH_OPPORTUNITIES = 'SEARCH_OPPORTUNITIES';
    static SEARCH_OPPORTUNITIES_SUCCESS = 'SEARCH_OPPORTUNITIES_SUCCESS';
    static SEARCH_OPPORTUNITIES_FAILED = 'SEARCH_OPPORTUNITIES_FAILED';

    static GET_OPPORTUNITY = 'GET_OPPORTUNITY';
    static GET_OPPORTUNITY_SUCCESS = 'GET_OPPORTUNITY_SUCCESS';
    static GET_OPPORTUNITY_FAILED = 'GET_OPPORTUNITY_FAILED';

    static APPLY_FOR_AN_OPPORTUNITY = 'APPLY_FOR_AN_OPPORTUNITY';
    static APPLY_FOR_AN_OPPORTUNITY_SUCCESS = 'APPLY_FOR_AN_OPPORTUNITY_SUCCESS';
    static APPLY_FOR_AN_OPPORTUNITY_FAILED = 'APPLY_FOR_AN_OPPORTUNITY_FAILED';

    // static GET_OPPORTUNITIES = 'GET_OPPORTUNITIES';
    // static GET_OPPORTUNITIES_SUCCESS = 'GET_OPPORTUNITIES_SUCCESS';
    // static GET_OPPORTUNITIES_FAILED = 'GET_OPPORTUNITIES_FAILED';

    // static GET_OPPORTUNITY_TYPE_COUNT = 'GET_OPPORTUNITY_TYPE_COUNT';
    // static GET_OPPORTUNITY_TYPE_COUNT_SUCCESS = 'GET_OPPORTUNITY_TYPE_COUNT_SUCCESS';
    // static GET_OPPORTUNITY_TYPE_COUNT_FAILED = 'GET_OPPORTUNITY_TYPE_COUNT_FAILED';

    // static GET_APPLIED_OPPORTUNITIES = 'GET_APPLIED_OPPORTUNITIES';
    // static GET_APPLIED_OPPORTUNITIES_SUCCESS = 'GET_APPLIED_OPPORTUNITIES_SUCCESS';
    // static GET_APPLIED_OPPORTUNITIES_FAILED = 'GET_APPLIED_OPPORTUNITIES_FAILED';

}
