export class SearchActions {

  static SEARCH_WIKI_PROFILES = 'SEARCH_WIKI_PROFILES';
  static SEARCH_WIKI_PROFILES_SUCCESS = 'SEARCH_WIKI_PROFILES_SUCCESS';
  static SEARCH_WIKI_PROFILES_FAILED = 'SEARCH_WIKI_PROFILES_FAILED';

  static SEARCH_ALL = 'SEARCH_ALL';
  static SEARCH_ALL_FAILED = 'SEARCH_ALL_FAILED';
  static SEARCH_ALL_SUCCESS = 'SEARCH_ALL_SUCCESS';

  static SEARCH_PEOPLE = 'SEARCH_PEOPLE';
  static SEARCH_PEOPLE_SUCCESS = 'SEARCH_PEOPLE_SUCCESS';
  static SEARCH_PEOPLE_FAILED = 'SEARCH_PEOPLE_FAILED';

  static SEARCH_POST = 'SEARCH_POST';
  static SEARCH_POST_SUCCESS = 'SEARCH_POST_SUCCESS';
  static SEARCH_POST_FAILED = 'SEARCH_POST_FAILED';

  static SEARCH_CHANNEL = 'SEARCH_CHANNEL';
  static SEARCH_CHANNEL_SUCCESS = 'SEARCH_CHANNEL_SUCCESS';
  static SEARCH_CHANNEL_FAILED = 'SEARCH_CHANNEL_FAILED';

  static SEARCH_OPPORTUNITY = 'SEARCH_OPPORTUNITY';
  static SEARCH_OPPORTUNITY_SUCCESS = 'SEARCH_OPPORTUNITY_SUCCESS';
  static SEARCH_OPPORTUNITY_FAILED = 'SEARCH_OPPORTUNITY_FAILED';

  static SEARCH_EVENT = 'SEARCH_EVENT';
  static SEARCH_EVENT_SUCCESS = 'SEARCH_EVENT_SUCCESS';
  static SEARCH_EVENT_FAILED = 'SEARCH_EVENT_FAILED';

}
