export class SharedActions {

  static GET_REPORT_OPTIONS = 'GET_REPORT_OPTIONS';
  static GET_REPORT_OPTIONS_SUCCESS = 'GET_REPORT_OPTIONS_SUCCESS';
  static GET_REPORT_OPTIONS_FAILED = 'GET_REPORT_OPTIONS_FAILED';

  static PIN_CHANNEL = 'PIN_CHANNEL';
  static PIN_CHANNEL_SUCCESS = 'PIN_CHANNEL_SUCCESS';
  static PIN_CHANNEL_FAILED = 'PIN_CHANNEL_FAILED';

  static UNPIN_CHANNEL = 'UNPIN_CHANNEL';
  static UNPIN_CHANNEL_SUCCESS = 'UNPIN_CHANNEL_SUCCESS';
  static UNPIN_CHANNEL_FAILED = 'UNPIN_CHANNEL_FAILED';

}
