export class SharedActions {

  static POST_SELECTED_OPTION = 'POST_SELECTED_OPTION';
  static POST_SELECTED_OPTION_SUCCESS = 'POST_SELECTED_OPTION_SUCCESS';
  static POST_SELECTED_OPTION_FAILED = 'POST_SELECTED_OPTION_FAILED';

  static GET_OPTIONS_REPORT = 'GET_OPTIONS_REPORT';
  static GET_OPTIONS_REPORT_SUCCESS = 'GET_OPTIONS_REPORT_SUCCESS';
  static GET_OPTIONS_REPORT_FAILED = 'GET_OPTIONS_REPORT_FAILED';

  static PIN_CHANNEL = 'PIN_CHANNEL';
  static PIN_CHANNEL_SUCCESS = 'PIN_CHANNEL_SUCCESS';
  static PIN_CHANNEL_FAILED = 'PIN_CHANNEL_FAILED';

  static UNPIN_CHANNEL = 'UNPIN_CHANNEL';
  static UNPIN_CHANNEL_SUCCESS = 'UNPIN_CHANNEL_SUCCESS';
  static UNPIN_CHANNEL_FAILED = 'UNPIN_CHANNEL_FAILED';

}
