export class UserSearchActions {

  static USER_SEARCH = 'USER_SEARCH';
  static USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
  static USER_SEARCH_FAILED = 'USER_SEARCH_FAILED';

  static MESSAGE_USER_SEARCH = 'MESSAGE_USER_SEARCH';
  static MESSAGE_USER_SEARCH_SUCCESS = 'MESSAGE_USER_SEARCH_SUCCESS';
  static MESSAGE_USER_SEARCH_FAILED = 'MESSAGE_USER_SEARCH_FAILED';

}
